# Account IDs and SSO profile names.
# NB: Enter the SSO profile name, not the account name.
# Below, they happen to be the same, which is quite OK.
# The profiles must have SystemAdministrator privileges.
#

admin-account.id               = "111111111111"
admin-account.profile          = "Org"

security-account.id            = "222222222222"
security-account.profile       = "Security-Adm"

log-archive-account.id         = "333333333333"
log-archive-account.profile    = "Log-Archive"

aft-management-account.id      = "444444444444"
aft-management-account.profile = "AFT-Management"

audit-account.id               = "555555555555"
audit-account.profile          = "Audit"
